CREATE TABLE BARCOS 
(
  FILA NUMBER DEFAULT 0 NOT NULL 
, COLUMNA NUMBER DEFAULT 0 NOT NULL 
, SENTIDO NUMBER DEFAULT 0 NOT NULL 
, IDBARCO NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT BARCOS_PK PRIMARY KEY 
  (
    FILA 
  , COLUMNA 
  )
  ENABLE 
);
